language: java
jdk:
  - openjdk7

before_install:
  - mkdir -p Modbus/src/main
  - ln -s Modbus/src/atrem/modbus/ Modbus/src/main/java
  - ls
  - gradle check

script: 
  - gradle compileJava
  - gradle jar
    
branches:
  only:
    - master